name: Testing

on:
  push:
    branches:
      - llm

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: "9"
          platform: x64

      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: "11.2.2"

      - name: Verify CUDA installation
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V
          sudo apt install -y --no-install-recommends nvidia-cudnn

      - name: coverage
        run: >
          LD_LIBRARY_PATH=${{steps.cuda-toolkit.outputs.CUDA_PATH}}/lib64{LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
          PATH=${{steps.cuda-toolkit.outputs.CUDA_PATH}}/bin${PATH:+:${PATH}}
          CUDA_HOME=${{steps.cuda-toolkit.outputs.CUDA_PATH}}
          bash -ex scripts/test.sh
